### ISSUE TITLE
How many people use Fountain?  (apology within)

### ISSUE THREAD

**Issue by jim-at-miramontes** [nyousefi/Fountain#18]
I APOLOGIZE IN ADVANCE for posting this here, since it really isn't what Github is about, but I've looked all over the place and can't find anywhere else to post this.  If someone can point me to a better place, I'd really appreciate it.  Meanwhile:

Is there any data out there indicating how many people are using Fountain?  I'm trying to make a case to my co-workers about using Fountain as the basis for some new application work, but without any sort of usage data, it's hard to make a convincing case.  Does anybody have anything relevant or useful?  Apologies again, and thanks!

**Comment by FibreFoX** [comment]
Despite of "how many users" there is support from some popular screenwriting applications, there are even some wikipedia-articles about:
- https://en.wikipedia.org/wiki/Fountain_%28markup_language%29#Implementations
- https://en.wikipedia.org/wiki/Screenwriting_software#List_of_software (there are some with Fountain-support)

The counter itself isn't proving anything for real, but you can look at the star-counter of this project, some of them might use the Fountain-language, and some others don't use github to add a star ;)

**Comment by davemh** [comment]
I think the star on github only represents a tiny fraction of actual users. The fact that Amazon Storywriter supports Fountain is a clue at the size of your potential audience.

You might want to [reach out to John August directly](http://johnaugust.com/ask-a-question) about this. I'd also recommend contacting the developers of the apps listed [on the Fountain site](http://fountain.io/apps), particularly Slugline and Logline, as both are excellent, and both rely on Fountain as a native format instead of just an import/export option.

**Comment by nyousefi** [comment]
We don't have any concrete data on how prevalent Fountain is (we don't even know how we could reliably get that sort of data), but I will echo the sentiment already expressed that it's pretty popular. Aside from John, who created the format, there are numerous professional screenwriters working in Fountain now, and most screenwriting apps (and an increasing number of Markdown apps) support reading and writing Fountain files.

Best of luck!

**Comment by jim-at-miramontes** [comment]
Thanks for the comments!  I'll be digging into the pointers as plans here proceed.
